### ISSUE TITLE
Beautify/format output html file

### ISSUE THREAD

**Issue by vladshcherbin** [rosenbjerg/rollup-plugin-html-bundle#1]
Hey 👋 

It would be nice if output html is formatted/beautified. I'm using `inline` option and indentation is broken where inline script is added.

Thanks

**Comment by rosenbjerg** [comment]
That would be nice but would require extra dependencies, which i would like to avoid unless needed. Would configurable indentation be sufficient to allow you to create html files you are happy with?

**Comment by vladshcherbin** [comment]
@rosenbjerg I actually don't remember, ended up with creating rollup plugin as none existing could do this and got no response in issues. Feel free to close, it's kinda solved for me :)

**Comment by rosenbjerg** [comment]
Okay, good to hear you found another solution.
Out of interest, why did the indentation matter - as long as it is valid of course? :)

**Comment by vladshcherbin** [comment]
@rosenbjerg just a personal preference :)

**Comment by rosenbjerg** [comment]
Okay, that's fair :)
