### ISSUE TITLE
Is there a way to watch the template on save?

### ISSUE THREAD

**Issue by thomas-lowry** [rosenbjerg/rollup-plugin-html-bundle#2]
This rollup plugin has been really useful! I was wondering if there is a way to set this up so that changes to the template.html will get reflected when I run `npm run dev` and re-bundle with the changes to the html file.

Right now I have to `run npm build`, or rerun the dev command to have any changes reflected.

```Javascript
export default [{
	input: 'src/ui/ui.js',
	output: {
		format: 'iife',
		name: 'ui',
		file: 'src/ui/build/bundle.js'
	},
	plugins: [
		resolve({
			browser: true,
		}),
		commonjs(),
		svg(),
		postcss({
			plugins: [ cssnano() ]
		}),
		htmlBundle({
            template: 'src/ui/ui.html',
            target: 'public/index.html',
			inline: true
		}),
```

**Comment by rosenbjerg** [comment]
That would be really nice, but I don't know of a way of adding a file to rollup's "watch list" without having to import it in a javascript file.
Would gladly accept a PR with that, if you know how to do that :)
